# Generated by Django 3.2.9 on 2021-11-08 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla_estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('endereco', models.CharField(blank=True, max_length=150)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade_vagas', models.IntegerField()),
                ('escolaridade_exigida', models.CharField(max_length=150)),
                ('data_inscricao', models.DateTimeField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa')),
                ('tipo_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipovaga')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
