# Generated by Django 3.2.9 on 2021-11-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='image',
            field=models.FileField(blank=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2021-11-10'),
            preserve_default=False,
        ),
    ]
