# Generated by Django 3.2.9 on 2021-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='foto',
            field=models.FileField(blank=True, upload_to='cidades/'),
        ),
    ]
