# Generated by Django 3.2.9 on 2021-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cidade_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default='emailqualquer@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
