# Generated by Django 3.2.9 on 2021-11-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_vaga_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logotipo',
            field=models.FileField(blank=True, upload_to='logotipo/'),
        ),
    ]
