# Generated by Django 3.2.9 on 2021-11-26 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_empresa_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
