# Generated by Django 3.2.9 on 2021-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vaga_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
